spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
  datasource:
    # ImMemory
    url: jdbc:h2:mem:paymentDB
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:paymentDB
    username: sa
    password:
  h2.console.enabled: true